- name: Copying mongodb repo file
  ansible.builtin.copy:
    src: mongod.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.yum:
    name: mongodb-org 
    state: present

- name: Updating mongodb config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB Service 
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: yes