- name: Copying mongodb repo file
  ansible.builtin.copy:
    src: mongod.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.yum:
    name: mongodb-org 
    state: present

- name: Updating mongodb config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB Service 
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: yes

- name: Donwload and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Loading cataloge schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes 
  loop: #with item is the key word for loop earlier now its loop itself
      - catalogue 
      - users


# - name: Loading cataloge schema
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/catalogue.js"
#     idempotent: yes 

# - name: Loading Users schema
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/users.js"
#     idempotent: yes