- name: Demo on facts
  hosts: all # all is default group in inventory file which includes everything
  tasks: 
    - name: Printing URL
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}

    - name: Printing mac address
      ansible.builtin.debug:
        msg: Mac address is {{ansible_default_ipv4.macaddress}}