- name: demo on outputs
  hosts: all
  tasks:
    - name: Printing a shell command
      ansible.builtin.shell: uptime 
      register: OUT 

    - name: printing out variable
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}" 

    - name: printing the uptime status 
      ansible.builtin.debug:
        msg: status of uptime is {{OUT.rc}}

# set_fact is depricated in version 6, which used to work on version 2.9

  #  - name: Declaring the variable
  #    set_fact:
  #      STATUS: "{{OUT.rc}}"
   
      