- name: Installing Maven
  ansible.builtin.package:
    name: maven
    state: present

- name: Creating Application user
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Donwload and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Generating package
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  become_user: "{{APPUSER}}"
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name:  Configuring the {{COMPONENT}} svc
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd-start-svc
