- name: Configure the yum repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | sudo bash

- name: Install NodeJs
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  loop:
    - nodejs 
    - gcc-c++

- name: Creating Application user
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user
 # We can even remove the comment part

- name: Cleanup of old component
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent
  
- name: Donwload and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download-and-extract

- name: Copying {{COMPONENT}} to {{APPUSER}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name:  Configuring the {{COMPONENT}} svc
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd-start-svc

- name:  Configuring the system name
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname

# - name: Copying systemd file 
#   ansible.builtin.copy:
#     src: systemd.service
#     dest: /etc/systemd/system/{{COMPONENT}}.service

# - name: Starting {{COMPONENT}} Service
#   ansible.builtin.systemd:
#     name: "{{COMPONENT}}"
#     state: restarted
#     enabled: yes
#     daemon_reload: yes