- name: Installing Python3
  ansible.builtin.yum: 
    name: 
      - python36
      - gcc
      - python3-devel
    state: installed 

- name: Creating application user
  ansible.builtin.include_role:
    name: common 
    tasks_from: create-user

- name:  Download and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download-and-extract 

- name: Installing {{COMPONNET}} Dependencies 
  ansible.builtin.pip: 
     requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
     executable: pip3

